import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

df1 = pd.read_csv('BCG.csv',na_values='n.a')
df2 = pd.read_csv('DPT.csv',na_values='n.a')
df3 = pd.read_csv('campak.csv',na_values='n.a')
df4 = pd.read_csv('polio.csv',na_values='n.a')

df1 = df1.interpolate()
df2 = df2.interpolate()
df3 = df3.interpolate()
df4 = df4.interpolate()

plt.figure('Persentasi balita terimunisasi 1995-2017', figsize =(13,9))
plt.subplot(2,2,1)
plt.bar(df1['Tahun'],df1['% Balita yang pernah mendapat imunisasi BCG'],color ='red')
plt.title('BCG')
plt.xticks(df1['Tahun'],np.arange(1995,2018),rotation = 90)
plt.subplot(2,2,2)
plt.bar(df2['Tahun'],df2['% Balita yang pernah mendapat imunisasi Campak'],color ='green')
plt.title('Campak')
plt.xticks(df2['Tahun'],np.arange(1995,2018),rotation = 90)
plt.subplot(2,2,3)
plt.bar(df3['Tahun'],df3['% Balita yang pernah mendapat imunisasi DPT'],color ='yellow')
plt.title('DPT')
plt.xticks(df3['Tahun'],np.arange(1995,2018),rotation = 90)
plt.subplot(2,2,4)
plt.bar(df4['Tahun'],df4['% Balita yang pernah mendapat imunisasi Polio'],color ='blue')
plt.title('Polio')
plt.xticks(df4['Tahun'],np.arange(1995,2018),rotation = 90)
plt.tight_layout()

plt.figure('Persentase balita tak terimunisasi 1995-2017', figsize =(13,9))
plt.subplot(2,2,1)
plt.bar(df1['Tahun'],100 - df1['% Balita yang pernah mendapat imunisasi BCG'],color ='red')
plt.title('BCG')
plt.xticks(df1['Tahun'],np.arange(1995,2018),rotation = 90)
plt.subplot(2,2,2)
plt.bar(df2['Tahun'],100 - df2['% Balita yang pernah mendapat imunisasi Campak'],color ='green')
plt.title('Campak')
plt.xticks(df2['Tahun'],np.arange(1995,2018),rotation = 90)
plt.subplot(2,2,3)
plt.bar(df3['Tahun'],100 - df3['% Balita yang pernah mendapat imunisasi DPT'],color ='yellow')
plt.title('DPT')
plt.xticks(df3['Tahun'],np.arange(1995,2018),rotation = 90)
plt.subplot(2,2,4)
plt.bar(df4['Tahun'],100 - df4['% Balita yang pernah mendapat imunisasi Polio'],color ='blue')
plt.title('Polio')
plt.xticks(df4['Tahun'],np.arange(1995,2018),rotation = 90)
plt.tight_layout()
plt.show()